name: "run-qa-tests"
description: "run-qa-tests"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Poetry - Install Dependencies
      uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/poetry__install@dev
      with:
        pip_install: '-r requirements-test.txt'

    - name: Run Unit Tests (using Poetry)
      uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/poetry__run-unit-tests@dev
      with:
        test_target: 'tests/integration'
      env:
        TARGET_SERVER: 'https://a4sbatx723cfs7tw3kbiifv37q0evpcp.lambda-url.eu-west-1.on.aws'
