name: "run-unit-and-integration-tests"
description: "run-unit-and-integration-tests"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Start Lambda Docker
      uses: ./.github/actions/docker__start-lambda-docker

    - name: Poetry - Install Dependencies
      uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/poetry__install@dev
      with:
        pip_install: '-r requirements-test.txt'

    - name: Run Unit Tests (using Poetry)
      uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/poetry__run-unit-tests@dev
      with:
        test_target: 'tests'

    - name: Stop Lambda Docker
      uses: ./.github/actions/docker__stop-lambda-docker