services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"  # Edge port for all services
      - "4510-4559:4510-4559"  # Service-specific ports (Lambda uses some of these)
    environment:
      - SERVICES=s3,lambda  # Enable both S3 and Lambda
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock  # Required for Lambda Docker execution

volumes:
  localstack_data:

networks:
  localstack_network:
    driver: bridge
