name: "docker__start-lambda-docker"
description: "Start Lambda Docker"

runs:
  using: "composite"
  steps:
    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@v3

    - name: Git Update Current Branch
      uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__update_branch@dev

    - name: Set $Version from file
      uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__read_version@dev

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: "${{env.DOCKER__CONTEXT}}"
        file   : "${{env.DOCKER__FILE__FOR_TESTS}}"
        push   : false
        load   : true
        tags   : | 
          ${{ env.DOCKER_HUB__USERNAME }}/${{ env.PACKAGE_NAME }}:${{env.VERSION}}
          ${{ env.DOCKER_HUB__USERNAME }}/${{ env.PACKAGE_NAME }}:latest
        build-args: |
          VERSION=${{ env.VERSION }}    

    - name: "Run Docker Container"
      shell: bash
      #run: |
      #  docker run --name ${{env.PACKAGE_NAME}} -p ${{env.DOCKER__HTTP_PORT}}:8080 -d ${{ env.DOCKER_HUB__USERNAME }}/${{ env.PACKAGE_NAME }}:${{env.VERSION}}
      run: |
        docker run --name ${{env.PACKAGE_NAME}} \
          -p ${{env.DOCKER__HTTP_PORT}}:8080 \
          -e LAMBDA_SHELL__AUTH_KEY=${{ env.LAMBDA_SHELL__AUTH_KEY }} \
          -d ${{ env.DOCKER_HUB__USERNAME }}/${{ env.PACKAGE_NAME }}:${{env.VERSION}}  
