name: "docker__start-lambda-docker"
description: "Start Lambda Docker"

runs:
  using: "composite"
  steps:
    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@v3


    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: "${{env.DOCKER__CONTEXT}}"
        file   : "${{env.DOCKER__FILE}}"
        push   : false
        load   : true
        tags   : | 
          ${{ env.DOCKER_HUB__USERNAME }}/${{ env.PACKAGE_NAME }}:${{env.VERSION}}
          ${{ env.DOCKER_HUB__USERNAME }}/${{ env.PACKAGE_NAME }}:latest
        build-args: |
          VERSION=${{ env.VERSION }}

    - name: "Check docker #2"
      shell: bash
      run: |        
        docker images

    - name: "Run Docker Container"
      shell: bash
      run: |
        docker run --name my_lambda_container -d ${{ env.DOCKER_HUB__USERNAME }}/${{ env.PACKAGE_NAME }}:${{env.VERSION}}

    - name: "Verify Docker Container Running"
      shell: bash
      run: |
        docker ps -a

    - name: "Show Container Logs"
      shell: bash
      run: |
        docker logs my_lambda_container
