name: "docker__start-prefect-server"
description: "docker__start-prefect-server"

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Docker Compose
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    - name: Start Docker Compose
      shell: bash
      working-directory: ./deploy/docker/prefect-server-v2
      run: | 
        docker-compose up -d

    - name: Wait for Prefect to be ready
      shell: bash
      run: |        
        for i in {1..20}; do
          if curl -s http://localhost:4200/api/health; then
            echo "Prefect is ready"
            break
          fi
          echo "Waiting for Prefect..."
          sleep 5
        done