name: "docker__start-lambda-docker"
description: "Start Lambda Docker"

runs:
  using: "composite"
  steps:
    # Set up Docker Buildx for better build performance and features
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3


    # Install Docker Compose
    - name: Install Docker Compose
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    # Navigate to the docker-compose file location and start the services
    - name: Start Docker Compose
      shell: bash
      working-directory: ./deploy/docker/prefect-server-v2
      run: | 
        docker-compose up -d

    # Wait for services to be up and running
#    - name: Wait for services
#      shell: bash
#      run: |
#        echo "Waiting for services to be up..."
#        sleep 30

    # Test Prefect service to see if it's running
    - name: Test Prefect API
      shell: bash
      run: |
        curl --retry 20 --retry-delay 5 --retry-connrefused -v http://localhost:4200/api/health
        docker logs  prefect-server
