services:
  prefect:
    image: prefecthq/prefect:2-latest
    container_name: prefect-orion
    environment:
      - PREFECT_API_HOST=0.0.0.0
      - PREFECT_API_PORT=4200
    ports:
      - "4200:4200"
    command: prefect server start --host 0.0.0.0 --port 4200

  postgres:
    image: postgres:13
    container_name: prefect-postgres
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect_db
    volumes:
      - prefect_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  prefect_postgres_data:
