name: "docker__stop-lambda-docker"
description: "Stop Lambda Docker"

runs:
  using: "composite"
  steps:

    - name: Stop and Remove Docker Container
      shell: bash
      if: always()
      run: |
        docker stop ${{PACKAGE_NAME}} || true
        docker rm   ${{PACKAGE_NAME}} || true