name: "docker__stop-lambda-docker"
description: "Stop Lambda Docker"

runs:
  using: "composite"
  steps:

#    - name: "Show Container Logs"
#      shell: bash
#      run: |
#        docker logs ${{env.PACKAGE_NAME}}

    - name: Stop and Remove Docker Container
      shell: bash
      if: always()
      run: |
        docker stop ${{env.PACKAGE_NAME}} || true
        docker rm   ${{env.PACKAGE_NAME}} || true