name: "docker__stop-lambda-docker"
description: "Stop Lambda Docker"

runs:
  using: "composite"
  steps:

    - name: "Verify Docker Container Running"
      shell: bash
      run: |
        docker ps -a

    - name: "Show Container Logs"
      shell: bash
      run: |
        docker logs my_lambda_container

    - name: Stop and Remove Docker Container
      shell: bash
      if: always()
      run: |
        docker stop my_lambda_container || true
        docker rm my_lambda_container || true