name       : CI Pipeline - DEV
on:
  workflow_dispatch:
  push:
    branches:
      - dev

env:
  RELEASE_TYPE         : 'minor'
  PACKAGE_NAME         : 'osbot_serverless_flows'
  DOCKER__CONTEXT      : "."
  DOCKER__FILE         : './deploy/docker/osbot-serverless-flows/Dockerfile'
  DOCKER_HUB__USERNAME : "diniscruz"
  VERSION              : '0.4.0'

jobs:
  docker__start-lambda-docker:
    name: Start Docker - Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Lambda Docker
        uses: .github/actions/docker__start-lambda-docker


  run-unit-tests:
    if: False
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Poetry - Install Dependencies
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/poetry__install@dev
        with:
          pip_install: '-r requirements-test.txt'

      - name: Run Unit Tests (using Poetry)
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/poetry__run-unit-tests@dev
        with:
          test_target: 'tests'

  increment-tag:
    name: Increment Tag - DEV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Increment Tag (for DEV)
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__increment-tag@dev
        with:
          release_type: ${{ env.RELEASE_TYPE }}
    needs:
      - run-unit-tests

  publish-to-pypi:
    if: False
    name: "Publish to: PYPI"
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Git Update Current Branch
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__update_branch@dev

      - name: publish-to-pypi
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/pypi__publish@dev
    needs:
      - increment-tag
