name : CI Pipeline - DEV
on:
  workflow_dispatch:
  push:
    branches:
      - dev

env:
  GIT__BRANCH                : 'dev'
  RELEASE_TYPE               : 'minor'
  PACKAGE_NAME               : 'osbot_serverless_flows'
  DOCKER__CONTEXT            : "."
  DOCKER__HTTP_PORT          : 5002
  DOCKER__FILE               : './deploy/docker/osbot-serverless-flows/Dockerfile'
  DOCKER__FILE__FOR_TESTS    : './deploy/docker/osbot-serverless-flows__integration-tests/Dockerfile'
  DOCKER_HUB__TOKEN          : ${{ secrets.DOCKER_HUB__TOKEN      }}
  DOCKER_HUB__USERNAME       : "diniscruz"
  LAMBDA_SHELL__AUTH_KEY     : ${{ secrets.LAMBDA_SHELL__AUTH_KEY }}

  PREFECT_CLOUD__API_KEY     : ${{ secrets.PREFECT_CLOUD__API_KEY      }}
  PREFECT_CLOUD__ACCOUNT_ID  : ${{ secrets.PREFECT_CLOUD__ACCOUNT_ID   }}
  PREFECT_CLOUD__WORKSPACE_ID: ${{ secrets.PREFECT_CLOUD__WORKSPACE_ID }}

  GSUITE__OAUTH2__DATA       : ${{ secrets.GSUITE__OAUTH2__DATA   }}
  GDRIVE__TEMP_FOLDER        : ${{ secrets.GDRIVE__TEMP_FOLDER    }}

jobs:


  run-unit-and-integration-tests:
    #if: False
    name: "Run Unit & Integration Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests and Integration Tests
        uses: ./.github/actions/pytest__run-unit-and-integration

  increment-tag:
    #if: False
    name: Increment Tag - DEV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Increment Tag
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__increment-tag@dev
        with:
          release_type: ${{ env.RELEASE_TYPE }}
    needs:
      - run-unit-and-integration-tests