name       : CI Pipeline - DEV
on:
  workflow_dispatch:
  push:
    branches:
      - dev

env:
  RELEASE_TYPE         : 'minor'
  PACKAGE_NAME         : 'osbot_serverless_flows'
  DOCKER__CONTEXT      : "."
  DOCKER__FILE         : './deploy/docker/osbot-serverless-flows/Dockerfile'
  DOCKER_HUB__USERNAME : "diniscruz"
  VERSION              : '0.4.0'
  GIT__BRANCH          : 'dev'

jobs:

  run-unit-and-integration-tests:
    # if: False
    name: Run Unit and Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start Lambda Docker
        uses: ./.github/actions/docker__start-lambda-docker

      - name: Poetry - Install Dependencies
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/poetry__install@dev
        with:
          pip_install: '-r requirements-test.txt'

      - name: Run Unit Tests (using Poetry)
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/poetry__run-unit-tests@dev
        with:
          test_target: 'tests'

      - name: Stop Lambda Docker
        uses: ./.github/actions/docker__stop-lambda-docker

  increment-tag:
    if: False
    name: Increment Tag - DEV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Increment Tag (for DEV)
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__increment-tag@dev
        with:
          release_type: ${{ env.RELEASE_TYPE }}
    needs:
      - run-unit-and-integration-tests

  publish-to-pypi:
    name: "Publish to: PYPI"
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Git Update Current Branch
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__update_branch@dev

      - name: publish-to-pypi
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/pypi__publish@dev
    needs:
      - increment-tag

  publish-to-aws-ecr:
    name: "Publish to: AWS ECR"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Wait for PyPI publish"
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/pypi__wait-for-publish@dev

      - name: "Publish to: AWS ECR"
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/aws__publish__ecr@dev
        env:
          AWS_ACCOUNT_ID       : '654654216424'
          AWS_ACCESS_KEY_ID    : ${{ secrets.AWS_ACCESS_KEY_ID__654654216424     }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY__654654216424 }}
          AWS_DEFAULT_REGION   : eu-west-1
    needs:
      - publish-to-pypi